FROM node:20-bookworm

WORKDIR /app

# Install dependencies required by Playwright
RUN apt-get update && apt-get install -y \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    && rm -rf /var/lib/apt/lists/*

# Указываем кастомную директорию для браузеров, чтобы избежать проблем с маунтами Jenkins
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# Install Playwright CLI globally to have access to the install command
RUN npm install -g playwright@1.42.1

# Install Playwright browser binaries
RUN npx playwright install --with-deps chromium

